### ISSUE TITLE
Register Domain

### ISSUE THREAD

**Issue by vietlq** [VISCHub/visc-website#1]
@vietlq

**Comment by tucq88** [comment]
`vischub.af` ? jk

**Comment by vietanh10** [comment]
visc.edu?

**Comment by vietlq** [comment]
@vietanh10 @tucq88 visc.network sounds good, and is pretty in line with other crypto tokens :D

**Comment by vietlq** [comment]
Done guys! So it will be http://visc.network ! I'm working on a Linode $5/m image :D
