### ISSUE TITLE
Pick tech stack for the front-end and back-end

### ISSUE THREAD

**Issue by vietlq** [VISCHub/visc-website#3]
Pick tech stack for the front-end and back-end

**Comment by tucq88** [comment]
Damn missed today meetup (again). For this, I think simply is the best, as following 2 options:
1/ Just static site, Hugo or Jekyll. Dynamic forms used by other 3rd services. 
2/ Or a bit complex with Wordpress, simple theme, simple development approach. 
PS: Do we have theme/template ready yet ?

**Comment by thanhson1085** [comment]
I vote using VueJS (Material Theme) in front-end, NodeJS (Express Framework) in backend.

Python also is OK for back-end. It is up to you, Viet. You should decide it early.

**Comment by tucq88** [comment]
`I vote using VueJS (Material Theme) in front-end, NodeJS (Express Framework) in backend.`
Sounds over-complex for a website (IMO). What features it (the website) gonna need?

**Comment by thanhson1085** [comment]
Wordpress is good framework for blog, but we need to have the registration flow as below:

![22829902_1699961640054331_6814423058240830611_o](https://user-images.githubusercontent.com/546540/32416007-ffdc932e-c274-11e7-8bda-c86fa79fc58c.jpg)

**Comment by tucq88** [comment]
Mehhh I don't know it's that complex./

**Comment by hophuochoanggia** [comment]
I like Koa.js for backend. On front end still prefer react than vue

**Comment by vietlq** [comment]
@dangkhoa141 @vietthaotran @vietanh10

**Comment by vietlq** [comment]
I had discussion with Thao, Viet Anh anh Khoa. We probably go with Meteor.com (MeteorJS) for back-end and React for front-end. @vietthaotran has suggested a few React UI frameworks.

Meteor.com has everything built-in, including OAuth, so that will simplify our development.

Express.js and Koa.js can be used later for REST API access :D 

Comments please.

**Comment by vietlq** [comment]
@tucq88 Registration requires only email/FB/GitHub. That should be enough for them to receive newsletter. Other steps are challenges and optional :D

**Comment by hkhoa** [comment]
MeteorJS and React seems like a good combination.  👍  💯

**Comment by vietlq** [comment]
So the domain is: http://visc.network :D

**Comment by vietlq** [comment]
After deliberation we decided to go with Express + Mongo + React. Everyone should develop on his/her PC first. One can use https://ngrok.com to show off his/her work to the world. If everything is fine, let's deploy your version to https://test.visc.network

@tucq88 @thanhson1085 @hophuochoanggia @dangkhoa141 @vietanh10 @dangkhoa141 @vietthaotran

**Comment by vietlq** [comment]
Finally we have arrived at Hugo https://gohugo.io for content :D Any dynamic apps can be done using NodeJS/Python and served via a separate sub-domain or URL.

@tucq88 @thanhson1085 @hophuochoanggia @dangkhoa141 @vietanh10 @dangkhoa141 @vietthaotran
